# Generated by Django 2.2.3 on 2019-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_app', '0002_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='website',
            field=models.URLField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
