# Generated by Django 2.2.3 on 2019-07-30 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_app', '0003_book_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='website',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
