# Generated by Django 2.2.3 on 2019-07-30 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books_app', '0004_auto_20190730_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
